import { useEffect, useState } from 'react'
import Head from "next/head";
import AdminLayout from "@/layouts/AdminLayout"
import AuthHOC from '@/components/AuthHOC'
import Table from '@/components/Table'
import { IAmbassador } from "@/interfaces"
import Button from '@/components/Button';
import { useRouter } from 'next/router';
import usePost from '@/hooks/usePost';
import { toast } from 'react-toastify';
import Loader from '@/components/Loader';
import { BiEdit } from 'react-icons/bi';
import { MdOutlineDelete } from 'react-icons/md';



const Ambassadors = () => {
  const [loading, setLoading] = useState(false)
  const [data, setData] = useState<IAmbassador[]>([])
  const router = useRouter()

  const { loading: posting, error, post, data: deleted } = usePost({ 
    api: "/ambassadors",
    method: "DELETE",
    onSuccess: () => {
        toast('Manager deleted successfully')
    } 
})

const deleteAmbassador = (id: string, route: string) => {
    post({
      id,
    }, route)
}




const colums = [
  {
    name: "name",
    label: "Name",
    options: {
      filter: true,
      sort: true,
    },
  },
  {
    name: "email",
    label: "Email",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "title",
    label: "Title",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "number",
    label: "Number",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "delete",
    label: "Action",
    extra: true,
    custom: (val: string, meta: any) => {
      return  (
        <div className="flex items-center gap-4 justify-left">
            {/* <button onClick={() => deleteAdvisory(meta?._id, `advisory/${meta?._id}`)} className="p-2 px-4 text-white bg-red-600 rounded-full">Delete</button> */}
          <BiEdit onClick={() => router.push(`/admin/management/${meta?._id}`)} size="1.2rem" className="cursor-pointer" />
          <MdOutlineDelete onClick={() => deleteAmbassador(meta?._id, `ambassadors/${meta?._id}`)} size="1.2rem" className="text-red-400 cursor-pointer" />
        </div>
      )
    },
  },
];

  useEffect(() => {
    const fetchUser = async () => {
      try {
        setLoading(true)
        const res = await fetch(`/api/ambassadors`)
        const data = await res.json()
        
        if (!res.ok) throw new Error(data.message)

        console.log({data})
        setData(data)
      } catch (error) {
        console.log({error})
      }
      setLoading(false)
    }

    fetchUser()
  }, [deleted])

  return (
    <AdminLayout>
      <Head>
        <title>Brilliant Brains</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconimg.png" />
      </Head>
      {(loading || posting) && <Loader modalOpen={true} />}
      <div className='h-full p-4 py-12 overflow-y-auto sm:px-12'>
        <div className="flex items-center justify-between gap-4 mb-16">
            <h1 className='text-3xl text-black/70 font-argentinum'>Management Team</h1>
            <Button onClick={() => router.push("/admin/management/add")} className="px-4 py-2 text-sm text-white sm:px-6 rounded-xl">Add Team Member</Button>
        </div>
        <Table<IAmbassador> data={data} columns={colums} className={''} />
      </div>
    </AdminLayout>
  );
}


export default AuthHOC(Ambassadors)

