import { Html, Head, Main, NextScript } from 'next/document'
import appConfig from '@/configs/app.config'

export default function Document() {
  return (
    <Html lang="en">
       <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className='text-black bg-white'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
